### ISSUE TITLE
total-count and duty cyle sensors ?

### ISSUE THREAD

**Issue by SeByDocKy** [syssi/esphome-total-count#7]
Hi @syssi,

Seems one more time your did a great job and maybe can fill the gap that the ESPhome duty cycle sensor is missing. It would be great if you can add a time option (s,m,d unity for exemple) to automatically reset the counting. In tis case, it can be an equivalent of the history stat HA sensor. Can be very usefull to make automation according to.

**Comment by syssi** [comment]
Could you explain your use case? I would like to add a reset service. How often the reset services is called can be controlled via automations (f.e. be the interval component or everytime the sensors reaches a specific values it resets to 0). So we can keep this component super generic.

**Comment by SeByDocKy** [comment]
> Could you explain your use case? I would like to add a reset service. How often the reset services is called can be controlled via automations (f.e. be the interval component or everytime the sensors reaches a specific values it resets to 0). So we can keep this component super generic.

Ok, I got a water pump and I definded a binary sensor like

```
binary_sensor:
   
  - platform: analog_threshold
    name: "puits_pompe_declenchement"
    id: puits_pompe_declenchement
    sensor_id: puits_pompe_puissance
    threshold:
      upper: 1000
      lower : 100
```

I want to count every day how many time this pump is started for example. I have many other application, for example in my alarme system, how many time this windows is opened per day, etc... many many applications..

**Comment by syssi** [comment]
I will add the reset service as first step. So you are able to reset the sensor f.e. once a day or every hour.

**Comment by SeByDocKy** [comment]
> I will add the reset service as first step. So you are able to reset the sensor f.e. once a day or every hour.

Sound already great :)
